### ISSUE TITLE
Re-work the build system to support multiple kernels at the same time and use a main branch

### ISSUE THREAD

**Issue by chp-io** [IntroVirt/kvm-introvirt#5]
**Existing problem**

The current build system uses the git branch name for versioning or for targeting a specific kernel version.
This prevents us from using a "main" branch, or to target multiple kernel versions for the same kvm-introvirt patch.
Another issue with this approach is the growing number of branch names polluting git objects.

**Solution / Summary**

Rework the build system so that it can support a main branch and be able to target multiple kernel versions.

**Acceptance Criteria**

- [x] A `main` branch should now be used
- [x] A directory structure in `patches` will be used to support multiple patch sets for specific kernel versions .e.g `./patches/ubuntu/focal/5.4/5.4.0-130.146`
  - [x] New sub-directories should only be created to resolve patch conflicts. Symbolic links should reuse applicable patch sets on newer kernels.
- [x] Patches should follow upstream repositories tags but an `available-headers.txt` file, listing the supported kernels, will be used to filter compatible builds, as header packages are not available for all kernels
- [x] Docker should be used in order to build any kernel version on the current host
- [x] Docker should be used to export the list of available headers for a distro
- The build script should provide:
  - [x] The ability to build all supported kernel versions at once
  - [x] The ability to build a module for a specific kernel version
  - [x] The ability to update the list of supported headers
  - [x] The ability to target a binary package, a source package, configuration only (apply patch)
- [ ] Update documentation to reflect changes

**Comment by laplante-sean** [comment]
Done.

I saw your draft PR. There's a lot in there that can be broken out into a new PR to add automated testing and whatnot. If you deconflict with the new main and get a new PR up that just focuses on the automated testing with qemu I'll review and merge
